apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: backend
        image: felipewind/broker-back-end:1.0
        ports:
        - containerPort: 8080
        env:
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: jdbc:postgresql://postgres:5432/postgres?currentSchema=exchange
          - name: QUARKUS_DATASOURCE_USERNAME
            value: postgres
          - name: QUARKUS_DATASOURCE_PASSWORD
            value: postgres
          - name: QUICKFIX
            value: |
              [default],
              [session],
              BeginString=FIX.4.4,
              SenderCompID=BANZAI,
              TargetCompID=EXEC,
              ConnectionType=initiator,
              StartTime=00:00:00,
              EndTime=00:00:00,
              ReconnectInterval=5,
              HeartBtInt=30,
              #SocketConnectHost=nyse,
              #SocketConnectPort=9880,
              SocketConnectHost=proxy,
              SocketConnectPort=10000,
              ScreenLogShowHeartBeats=Y,
              JdbcStoreMessagesTableName=messages,
              JdbcStoreSessionsTableName=sessions,
              JdbcLogHeartBeats=Y,
              JdbcLogIncomingTable=messages_log_incoming,
              JdbcLogOutgoingTable=messages_log_outgoing,
              JdbcLogEventTable=event_log,
              JdbcSessionIdDefaultPropertyValue=not_null
        resources:
          requests:
            memory: 512Mi
            cpu: 10m
          limits:
            memory: 512Mi
            cpu: 1000m
      - name: frontend
        image: arontsang/broker-front-end:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 16Mi
            cpu: 10m

---
kind: Service
apiVersion: v1
metadata:
  name: broker
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: ui
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: backend
  selector:
    app: broker
  type: LoadBalancer