apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fix-sim
metadata:
  name: FixSimulation
configMapGenerator:
  - name: init-sql
    files:
      - init-broker.sql
      - init-exchange.sql
resources:
  - broker.yaml
  - database.yaml
  - namespace.yaml
  - nyse.yaml
  - proxy.yaml