
[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
[target.armv7-unknown-linux-gnueabihf]
linker = "/usr/bin/arm-linux-gnueabihf-gcc"
[target.armv5te-unknown-linux-gnueabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"
[target.i686-unknown-linux-gnu]
linker = "/usr/bin/i686-linux-gnu-gcc"
[target.powerpc64le-unknown-linux-gnu]
linker = "/usr/bin/powerpc64le-linux-gnu-gcc"
[target.s390x-unknown-linux-gnu]
linker = "/usr/bin/s390x-linux-gnu-gcc"